"""
GUV Detector - Graphical User Interface (cleaned)
Interactive per-image calibration; processing starts only after calibration.

Batch mode: if the selected folder contains valid subfolders (excluding
previously generated 'processing_images*' folders):
  1. ALL images from ALL subfolders are pooled into a single processing_images
     folder under the root folder → one global inference run + global outputs.
  2. EACH subfolder is also processed independently → its own processing_images
     folder, CSV, PDF, JSON saved inside that subfolder.
Calibration is performed once (first image of first subfolder) and reused
for both the global run and all individual subfolder runs.
"""
import os
import math
import threading
import sys
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from PIL import Image, ImageTk
import ultralytics
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
from scipy.stats import lognorm
import numpy as np
import csv
import json

def resource_path(relative_path):
    if hasattr(sys, "_MEIPASS"):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)


# Prefix used to identify auto-generated subfolders (to be excluded from batch scan)
PROCESSING_FOLDER_PREFIX = "processing_images"


def is_generated_folder(name: str) -> bool:
    """Return True if a folder name was auto-generated by a previous run."""
    return name == PROCESSING_FOLDER_PREFIX or (
        name.startswith(PROCESSING_FOLDER_PREFIX + "_") and
        name[len(PROCESSING_FOLDER_PREFIX) + 1:].isdigit()
    )


class CalibrationWindow:
    """Modal window: click 2 points, enter real distance (um) -> returns mu_per_pixel"""
    def __init__(self, parent, image_path, image_name, default_mu):
        self.top = tk.Toplevel(parent)
        self.top.title(f"Calibrate: {image_name}")
        self.top.geometry("950x900")
        self.top.grab_set()  # modal
        self.parent = parent

        self.image_path = image_path
        self.image_name = image_name
        self.points = []
        self.pixel_distance = 0.0
        self.mu_per_pixel = None
        self.calibration_done = False
        self.default_mu = default_mu

        # load image and scale if large
        self.original_image = Image.open(image_path)
        self.display_image = self.original_image.copy()
        max_display = 800
        if max(self.display_image.size) > max_display:
            ratio = max_display / max(self.display_image.size)
            new_size = (int(self.display_image.size[0] * ratio),
                        int(self.display_image.size[1] * ratio))
            self.display_image = self.display_image.resize(new_size, Image.LANCZOS)
            self.scale_factor = ratio
        else:
            self.scale_factor = 1.0

        self._build_ui()

    def _build_ui(self):
        ttk.Label(self.top, text="Click TWO points on the image to define a known distance",
                  font=('Helvetica', 12, 'bold')).pack(pady=6)
        ttk.Label(self.top, text="Then enter the REAL distance in um and press Calculate",
                  font=('Helvetica', 10)).pack()

        canvas_frame = ttk.Frame(self.top)
        canvas_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        self.canvas = tk.Canvas(canvas_frame, width=self.display_image.width,
                                height=self.display_image.height, cursor='crosshair')
        self.canvas.pack()
        self.photo = ImageTk.PhotoImage(self.display_image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.photo)
        self.canvas.bind("<Button-1>", self.on_click)
        self.info_label = ttk.Label(self.top, text="Click FIRST point...",
                                    font=('Helvetica', 11), foreground='blue')
        self.info_label.pack(pady=4)

        entry_frame = ttk.Frame(self.top)
        entry_frame.pack(fill=tk.X, padx=10, pady=6)
        ttk.Label(entry_frame, text="Real distance (um):", font=('Helvetica', 11)).pack(side=tk.LEFT)
        self.distance_entry = ttk.Entry(entry_frame, width=12, font=('Helvetica', 11))
        self.distance_entry.pack(side=tk.LEFT, padx=6)
        self.distance_entry.config(state='disabled')

        btn_frame = ttk.Frame(self.top)
        btn_frame.pack(fill=tk.X, padx=10, pady=8)
        ttk.Button(btn_frame, text="Reset Points", command=self.reset_points).pack(side=tk.LEFT, padx=4)
        ttk.Button(btn_frame, text=f"Skip (use default {self.default_mu.get()})",
                   command=self.skip_calibration).pack(side=tk.LEFT, padx=4)
        ttk.Button(btn_frame, text="Calculate",
                   command=self.calculate_calibration).pack(side=tk.LEFT, padx=4)

        self.done_button = ttk.Button(btn_frame, text="DONE", command=self.confirm_calibration)
        self.done_button.pack(side=tk.RIGHT)
        self.done_button.config(state='disabled')

    def on_click(self, event):
        if len(self.points) >= 2:
            messagebox.showinfo("Info", "Two points already selected. Reset to pick new points.")
            return
        x, y = event.x, event.y
        self.points.append((x, y))
        r = 4
        self.canvas.create_oval(x-r, y-r, x+r, y+r,
                                fill='red', outline='yellow', width=2, tags='cal')
        self.canvas.create_text(x, y-14, text=f"P{len(self.points)}", fill='yellow',
                                font=('Helvetica', 10, 'bold'), tags='cal')
        if len(self.points) == 1:
            self.info_label.config(text="Click SECOND point...", foreground='blue')
        else:
            x0, y0 = self.points[0]
            x1, y1 = self.points[1]
            self.canvas.create_line(x0, y0, x1, y1, fill='yellow', width=3, tags='cal')
            dx = (x1 - x0) / self.scale_factor
            dy = (y1 - y0) / self.scale_factor
            self.pixel_distance = math.hypot(dx, dy)
            self.info_label.config(
                text=f"Pixel distance: {self.pixel_distance:.1f} px. "
                     f"Enter real distance and press Calculate.",
                foreground='green')
            self.distance_entry.config(state='normal')
            self.distance_entry.focus()

    def calculate_calibration(self):
        if len(self.points) < 2:
            messagebox.showwarning("Warning", "Select two points first.")
            return
        try:
            real_distance = float(self.distance_entry.get())
            if real_distance <= 0:
                raise ValueError("Distance must be > 0")
            self.mu_per_pixel = real_distance / self.pixel_distance
            self.info_label.config(
                text=f"Calibration: {self.mu_per_pixel:.4f} um/pixel",
                foreground='darkgreen')
            self.done_button.config(state='normal')
        except Exception as e:
            messagebox.showerror("Error", f"Invalid distance: {e}")

    def reset_points(self):
        self.points = []
        self.pixel_distance = 0.0
        self.mu_per_pixel = None
        self.canvas.delete('cal')
        self.info_label.config(text="Click FIRST point...", foreground='blue')
        self.distance_entry.delete(0, tk.END)
        self.distance_entry.config(state='disabled')
        self.done_button.config(state='disabled')

    def skip_calibration(self):
        if messagebox.askyesno("Skip calibration",
                               f"Skip calibration for {self.image_name}?\nDefault will be used."):
            self.mu_per_pixel = self.default_mu.get()
            self.done_button.config(state='normal')
            self.calibration_done = True
            self.top.destroy()

    def confirm_calibration(self):
        if self.mu_per_pixel is None:
            messagebox.showwarning("Warning", "Calculate or skip before confirming.")
            return
        self.calibration_done = True
        self.top.destroy()

    def get_calibration(self):
        self.top.wait_window()
        return self.mu_per_pixel if self.calibration_done else None


class GUVDetectorGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("GUV Detector with YOLOv11")
        self.root.geometry("1000x800")

        self.folder_path = tk.StringVar()
        self.model_size = tk.StringVar(value="n")
        self.modality = tk.StringVar(value="grey")
        self.split_factor = tk.IntVar(value=2)
        self.mu_per_pixel = tk.DoubleVar(value=0.339)
        self.conf_thresh = tk.DoubleVar(value=0.25)
        self.use_interactive_calibration = tk.BooleanVar(value=True)

        self.calibration_data = {}
        self._build_ui()

    # ------------------------------------------------------------------
    # UI
    # ------------------------------------------------------------------

    def _build_ui(self):
        main = ttk.Frame(self.root, padding=10)
        main.grid(row=0, column=0, sticky=(tk.N, tk.S, tk.E, tk.W))

        ttk.Label(main, text="GUV Detector", font=('Helvetica', 20, 'bold')).grid(
            row=0, column=0, columnspan=3, pady=6)

        ttk.Label(main, text="Image Folder:", font=('Helvetica', 12)).grid(
            row=1, column=0, sticky=tk.W)
        ttk.Entry(main, textvariable=self.folder_path, width=50).grid(
            row=1, column=1, padx=4, sticky=tk.W)
        ttk.Button(main, text="Browse...", command=self.browse_folder).grid(
            row=1, column=2, padx=4)

        ttk.Label(main, text="Model Size:", font=('Helvetica', 12)).grid(
            row=2, column=0, sticky=tk.W)
        ttk.Combobox(main, textvariable=self.model_size, values=["n","s","m","l","x"],
                     state='readonly', width=18).grid(row=2, column=1, sticky=tk.W)

        ttk.Label(main, text="Modality:", font=('Helvetica', 12)).grid(
            row=3, column=0, sticky=tk.W)
        ttk.Combobox(main, textvariable=self.modality, values=["rgb","grey"],
                     state='readonly', width=18).grid(row=3, column=1, sticky=tk.W)

        ttk.Label(main, text="Split factor:", font=('Helvetica', 12)).grid(
            row=4, column=0, sticky=tk.W)
        sf_frame = ttk.Frame(main)
        sf_frame.grid(row=4, column=1, sticky=tk.W)
        ttk.Radiobutton(sf_frame, text="2 (4)", variable=self.split_factor, value=2).pack(side=tk.LEFT)
        ttk.Radiobutton(sf_frame, text="4 (16)", variable=self.split_factor, value=4).pack(side=tk.LEFT)

        ttk.Label(main, text="Conf threshold:", font=('Helvetica', 12)).grid(
            row=5, column=0, sticky=tk.W)
        ttk.Entry(main, textvariable=self.conf_thresh, width=10).grid(
            row=5, column=1, sticky=tk.W)

        ttk.Label(main, text="um/pixel", font=('Helvetica', 12)).grid(
            row=6, column=0, sticky=tk.W)
        ttk.Entry(main, textvariable=self.mu_per_pixel, width=10).grid(
            row=6, column=1, sticky=tk.W)

        ttk.Checkbutton(main, text="Interactive calibration per image",
                        variable=self.use_interactive_calibration).grid(
            row=7, column=1, sticky=tk.W, pady=4)

        btn_frame = ttk.Frame(main)
        btn_frame.grid(row=8, column=0, columnspan=3, pady=8)
        self.run_button = ttk.Button(btn_frame, text="Run Detection", command=self.run_detection)
        self.run_button.pack(side=tk.LEFT, padx=6)
        self.reset_button = ttk.Button(btn_frame, text="Reset",
                                       command=self.reset_all, state='disabled')
        self.reset_button.pack(side=tk.LEFT, padx=6)

        self.progress = ttk.Progressbar(main, mode='determinate', length=420)
        self.progress.grid(row=9, column=0, columnspan=3, pady=6)

        self.status_label = ttk.Label(main, text="Ready", font=('Helvetica', 12))
        self.status_label.grid(row=10, column=0, columnspan=3, pady=4)

        self.notebook = ttk.Notebook(main)
        self.notebook.grid(row=11, column=0, columnspan=3,
                           sticky=(tk.N, tk.S, tk.E, tk.W), pady=6)
        result_frame = ttk.Frame(self.notebook, padding=8)
        self.notebook.add(result_frame, text="Text Results")
        self.result_text = tk.Text(result_frame, height=18, wrap=tk.WORD)
        self.result_text.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar = ttk.Scrollbar(result_frame, command=self.result_text.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.result_text.configure(yscrollcommand=scrollbar.set)

        self.plot_frame = ttk.Frame(self.notebook, padding=8)
        self.notebook.add(self.plot_frame, text="Size Distribution Plot")
        self.plot_placeholder = ttk.Label(self.plot_frame,
                                          text="Run detection to see the plot",
                                          font=('Helvetica', 14))
        self.plot_placeholder.pack(expand=True)

        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
        main.columnconfigure(1, weight=1)
        main.rowconfigure(11, weight=1)

    # ------------------------------------------------------------------
    # UI helpers
    # ------------------------------------------------------------------

    def browse_folder(self):
        f = filedialog.askdirectory(title="Select Image Folder")
        if f:
            self.folder_path.set(f)

    def append_result(self, txt):
        self.result_text.insert(tk.END, txt + "\n")
        self.result_text.see(tk.END)
        self.result_text.update_idletasks()

    def set_status(self, txt):
        self.status_label.config(text=txt)
        self.status_label.update_idletasks()

    def set_progress(self, value, maximum=100):
        self.progress['maximum'] = maximum
        self.progress['value'] = value
        self.progress.update_idletasks()

    def reset_all(self):
        self.result_text.delete(1.0, tk.END)
        for w in self.plot_frame.winfo_children():
            w.destroy()
        self.plot_placeholder = ttk.Label(self.plot_frame,
                                          text="Run detection to see the plot",
                                          font=('Helvetica', 14))
        self.plot_placeholder.pack(expand=True)
        self.calibration_data = {}
        self.set_status("Ready")
        self.set_progress(0, 100)
        self.run_button.config(state='normal')
        self.reset_button.config(state='disabled')

    # ------------------------------------------------------------------
    # Entry point
    # ------------------------------------------------------------------

    def run_detection(self):
        folder = self.folder_path.get()
        if not folder:
            messagebox.showerror("Error", "Select image folder first.")
            return
        if not os.path.exists(folder):
            messagebox.showerror("Error", "Folder not found.")
            return

        self.run_button.config(state='disabled')
        self.reset_button.config(state='disabled')
        self.result_text.delete(1.0, tk.END)
        for w in self.plot_frame.winfo_children():
            w.destroy()
        self.plot_placeholder = ttk.Label(self.plot_frame,
                                          text="Processing...", font=('Helvetica', 14))
        self.plot_placeholder.pack(expand=True)

        t = threading.Thread(target=self._worker_run, daemon=True)
        t.start()

    # ------------------------------------------------------------------
    # Main worker: global run (all images pooled) + per-subfolder runs
    # ------------------------------------------------------------------

    def _worker_run(self):
        try:
            root_folder = self.folder_path.get()
            self.current_folder_name = os.path.basename(os.path.normpath(root_folder))

            valid_ext = ('.png', '.jpg', '.jpeg')

            # ── Discover subfolders ─────────────────────────────────────────
            subfolders = []
            for entry in sorted(os.scandir(root_folder), key=lambda e: e.name):
                if not entry.is_dir():
                    continue
                if is_generated_folder(entry.name):
                    continue
                if any(f.lower().endswith(valid_ext) for f in os.listdir(entry.path)):
                    subfolders.append(entry.path)

            # ── Build flat image pool ───────────────────────────────────────
            if subfolders:
                self.append_result(
                    f"Batch mode: found {len(subfolders)} subfolder(s). "
                    f"Running global + individual analyses.")
                for sf in subfolders:
                    self.append_result(f"  - {os.path.basename(sf)}")
                image_sources = []
                for sf in subfolders:
                    imgs = sorted(f for f in os.listdir(sf) if f.lower().endswith(valid_ext))
                    for img in imgs:
                        image_sources.append((sf, img))
            else:
                self.append_result("Single-folder mode (no valid subfolders found).")
                imgs = sorted(f for f in os.listdir(root_folder)
                              if f.lower().endswith(valid_ext))
                image_sources = [(root_folder, img) for img in imgs]

            if not image_sources:
                raise RuntimeError("No image files found.")

            # ── Size consistency check ──────────────────────────────────────
            first_path = os.path.join(image_sources[0][0], image_sources[0][1])
            with Image.open(first_path) as im:
                ref_size = im.size

            valid_sources, rejected = [], []
            for src_folder, fname in image_sources:
                try:
                    with Image.open(os.path.join(src_folder, fname)) as im:
                        if im.size == ref_size:
                            valid_sources.append((src_folder, fname))
                        else:
                            rejected.append(fname)
                except Exception:
                    rejected.append(fname)

            if not valid_sources:
                raise RuntimeError("No valid images with consistent size found.")

            self.append_result(
                f"Found {len(valid_sources)} valid images. Rejected {len(rejected)} files.")
            for r in rejected:
                self.append_result(f"  - ignored: {r}")

            # ── Calibration: once for everything ───────────────────────────
            if self.use_interactive_calibration.get():
                self.append_result("\n=== CALIBRATION PHASE ===")
                first_folder, first_name = valid_sources[0]
                self.set_status(f"Calibrating using: {first_name}")
                calib = CalibrationWindow(
                    self.root,
                    os.path.join(first_folder, first_name),
                    first_name,
                    self.mu_per_pixel
                ).get_calibration()

                if calib is None:
                    raise RuntimeError("Calibration cancelled by user.")

                self.append_result(
                    f"Calibration: {calib:.4f} um/pixel — applied to ALL images.")
            else:
                calib = self.mu_per_pixel.get()
                self.append_result(f"Using default calibration: {calib} um/pixel")

            self.calibration_data = {fname: calib for _, fname in valid_sources}

            # ── Create ONE global processing folder under root ──────────────
            proc_folder = self._create_unique_folder(root_folder)
            self.append_result(f"\n=== GLOBAL RUN ===")
            self.append_result(f"Processing folder: {proc_folder}")

            # ── Split all images into global proc_folder ────────────────────
            self.set_status("Splitting images (global)...")
            self.append_result("\n=== SPLITTING IMAGES ===")
            total = len(valid_sources)
            self.set_progress(0, total)
            sf_n = int(self.split_factor.get())

            for idx, (src_folder, img_name) in enumerate(valid_sources, start=1):
                img = Image.open(os.path.join(src_folder, img_name))
                w, h = img.size
                step_w, step_h = w // sf_n, h // sf_n
                crop_idx = 0
                for i in range(sf_n):
                    for j in range(sf_n):
                        crop = img.crop((j * step_w, i * step_h,
                                         j * step_w + step_w, i * step_h + step_h))
                        if self.modality.get() == 'grey':
                            crop = crop.convert('L')
                        crop_name = f"{os.path.splitext(img_name)[0]}_crop{crop_idx + 1}.png"
                        crop.save(os.path.join(proc_folder, crop_name))
                        crop_idx += 1
                self.append_result(f"  [{idx}/{total}] {img_name} -> {crop_idx} crops")
                self.set_progress(idx, total)

            self.set_progress(0, 100)
            self.set_status("Splitting done.")

            # ── Load YOLO model ─────────────────────────────────────────────
            self.set_status("Loading model...")
            model_rel = os.path.join('model', self.modality.get(),
                                     f'yolo11_{self.model_size.get()}', 'best.pt')
            model_path = resource_path(model_rel)
            if not os.path.exists(model_path):
                raise RuntimeError(f"Model not found at: {model_path}")
            model = ultralytics.YOLO(model_path)

            # ── Global inference ────────────────────────────────────────────
            self.set_status("Running predictions (YOLO) — global...")
            img_list = [f for f in os.listdir(proc_folder)
                        if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
            n_imgs = len(img_list)
            if n_imgs == 0:
                raise RuntimeError("No cropped images to predict.")
            self.set_progress(0, n_imgs)

            results = model.predict(
                source=proc_folder, save=True, save_txt=True, save_conf=True,
                project=proc_folder, conf=float(self.conf_thresh.get()), stream=True
            )
            for idx, _ in enumerate(results, start=1):
                self.set_progress(idx, n_imgs)
                self.set_status(f"Predicting {idx}/{n_imgs}")

            self.set_status("Predictions done.")
            predict_root = os.path.join(proc_folder, 'predict')
            if not os.path.exists(predict_root):
                raise RuntimeError("YOLO did not produce a 'predict' folder.")

            # ── Global analysis ─────────────────────────────────────────────
            self.set_status("Analyzing predictions (global)...")
            self.append_result("\n=== GLOBAL ANALYSIS ===")
            labels_dir = os.path.join(predict_root, 'labels')
            if not os.path.exists(labels_dir):
                raise RuntimeError("No labels folder found in predictions.")

            label_files = sorted(f for f in os.listdir(labels_dir) if f.endswith('.txt'))
            total_labels = len(label_files)
            self.set_progress(0, max(total_labels, 1))

            dim_list = []
            count_edge = 0
            count_inter = 0

            for idx, lab in enumerate(label_files, start=1):
                lab_path = os.path.join(labels_dir, lab)
                base = os.path.splitext(lab)[0]
                img_candidate = None
                for ext in ('.png', '.jpg', '.jpeg'):
                    p = os.path.join(predict_root, base + ext)
                    if os.path.exists(p):
                        img_candidate = p
                        break
                if img_candidate is None:
                    self.append_result(f"  [warn] no image found for label {lab}")
                    self.set_progress(idx, total_labels)
                    continue

                mu = self._get_mu_for_cropped(os.path.basename(img_candidate))

                boxes = []
                with open(lab_path) as fh:
                    for line in fh:
                        parts = line.strip().split()
                        if len(parts) >= 6:
                            try:
                                _, xc, yc, wbox, hbox, conf = map(float, parts[:6])
                                if conf >= float(self.conf_thresh.get()):
                                    boxes.append((wbox, hbox))
                            except Exception:
                                continue

                if not boxes:
                    self.set_progress(idx, total_labels)
                    continue

                w_img, h_img = Image.open(img_candidate).size
                for wbox, hbox in boxes:
                    W = wbox * w_img
                    H = hbox * h_img
                    max_dim = max(W, H)
                    min_dim = min(W, H)
                    if min_dim <= 0.5 * max_dim:
                        count_edge += 1
                    else:
                        count_inter += 1
                    dim = np.sqrt(max_dim**2 + min_dim**2) / np.sqrt(2)
                    dim_list.append(dim * mu)

                self.set_progress(idx, total_labels)
                self.set_status(f"Analyzing {idx}/{total_labels}")

            # ── Global stats & plot ─────────────────────────────────────────
            if not dim_list:
                self.append_result("No GUVs detected across all images.")
                self.set_status("Complete (no GUVs).")
                self.set_progress(100, 100)
                self.reset_button.config(state='normal')
                return

            arr = np.array(dim_list)
            median = np.median(arr)
            q1 = np.percentile(arr, 25)
            q3 = np.percentile(arr, 75)
            try:
                shape, loc, scale = lognorm.fit(arr, floc=0)
                mu_ln = float(np.log(scale))
                sigma_ln = float(shape)
            except Exception:
                shape = loc = scale = None
                mu_ln = sigma_ln = float('nan')

            fig = Figure(figsize=(10, 6), tight_layout=True)
            ax = fig.add_subplot(111)
            bin_width = 5
            bins = np.arange(0, max(dim_list) + bin_width, bin_width)
            ax.hist(dim_list, bins=bins, color='chocolate', alpha=0.5, density=True)
            ax.axvline(median, color='darkred', linestyle='dashed', linewidth=3,
                       label=f'Median: {median:.2f} um')
            ax.axvline(q1, color='red', linestyle='dashed', linewidth=3,
                       label=f'Q1: {q1:.2f} um')
            ax.axvline(q3, color='red', linestyle='dashed', linewidth=3,
                       label=f'Q3: {q3:.2f} um')
            if shape is not None:
                x = np.linspace(0, max(dim_list), 1000)
                pdf = lognorm.pdf(x, shape, loc=loc, scale=scale)
                ax.plot(x, pdf, 'k-', linewidth=3,
                        label=(f'Log-normal fit\nmu={mu_ln:.2f}, sigma={sigma_ln:.2f}\n'
                               f'Total GUVs: {len(dim_list)}'))
            ax.set_xlabel('GUV Diameter (um)', fontsize=20)
            ax.set_ylabel('Density of GUVs', fontsize=20)
            ax.set_title(f"{self.current_folder_name} (global)", fontsize=16)
            ax.tick_params(axis='both', which='major', labelsize=16)
            ax.legend(fontsize=16)
            ax.grid(linestyle=':')

            plot_path = os.path.join(proc_folder, f'{self.current_folder_name}.pdf')
            fig.savefig(plot_path, dpi=300, bbox_inches='tight')
            self.root.after(0, lambda f=fig: self._show_plot(f))

            # Global CSV
            csv_path = os.path.join(proc_folder, f"{self.current_folder_name}.csv")
            with open(csv_path, mode='w', newline='') as csvfile:
                writer = csv.writer(csvfile)
                writer.writerow(["GUV_ID", "Diameter_um"])
                for i, diameter in enumerate(dim_list, start=1):
                    writer.writerow([i, f"{diameter:.4f}"])

            # Global JSON
            document_root, folder_path_out = self.create_json(proc_folder)
            self.append_result(f"\nPre-annotation information for Label Studio")
            self.append_result(f"Document root: {document_root}")
            self.append_result(f"Folder path: {folder_path_out}")

            # Global text summary
            self.append_result("\n=== GLOBAL RESULTS ===")
            self.append_result(f"Total GUVs detected: {len(arr)}")
            self.append_result(f"Edge: {count_edge}  |  Interior: {count_inter}")
            self.append_result(f"Median: {median:.2f} um  Q1: {q1:.2f} um  Q3: {q3:.2f} um")
            self.append_result(f"Log-normal  mu={mu_ln:.2f}, sigma={sigma_ln:.2f}")
            self.append_result(f"Calibration: {calib:.4f} um/pixel (global)")
            self.append_result(f"Plot saved:  {plot_path}")

            self.append_result(f"\n=== GUV dimensions (um) ===")
            for i in range(0, len(dim_list), 5):
                chunk = dim_list[i:i+5]
                self.append_result("  " + ", ".join(f"{d:.2f}" for d in chunk))

            # ── Individual subfolder runs ───────────────────────────────────
            if subfolders:
                self.append_result("\n" + "="*60)
                self.append_result("=== INDIVIDUAL SUBFOLDER ANALYSIS ===")
                self.append_result("="*60)
                for sf in subfolders:
                    sf_name = os.path.basename(sf)
                    self.append_result(f"\n[Subfolder: {sf_name}]")
                    self.set_status(f"Processing subfolder: {sf_name}")
                    self._run_single_folder(sf, calib)

            self.set_status("Complete")
            self.set_progress(100, 100)
            self.reset_button.config(state='normal')

        except Exception as e:
            self.root.after(0, lambda: messagebox.showerror("Error", str(e)))
            self.set_status(f"Error: {e}")
            self.append_result(f"[ERROR] {e}")
            self.reset_button.config(state='normal')
        finally:
            self.run_button.config(state='disabled')

    # ------------------------------------------------------------------
    # Individual subfolder pipeline (reuses already-computed calibration)
    # ------------------------------------------------------------------

    def _run_single_folder(self, folder: str, calib: float):
        """
        Run the full pipeline on a single subfolder using a pre-computed
        calibration value. Creates its own processing_images/ inside `folder`.
        Saves PDF, CSV and JSON there. Does NOT update the main UI plot.
        """
        folder_name = os.path.basename(os.path.normpath(folder))
        valid_ext = ('.png', '.jpg', '.jpeg')

        # collect images
        files = sorted(f for f in os.listdir(folder) if f.lower().endswith(valid_ext))
        if not files:
            self.append_result(f"  [SKIP] No images in {folder_name}")
            return

        # size consistency
        with Image.open(os.path.join(folder, files[0])) as im:
            ref_size = im.size
        valid_files, rejected = [], []
        for f in files:
            try:
                with Image.open(os.path.join(folder, f)) as im:
                    (valid_files if im.size == ref_size else rejected).append(f)
            except Exception:
                rejected.append(f)

        if not valid_files:
            self.append_result(f"  [SKIP] No consistent-size images in {folder_name}")
            return
        for r in rejected:
            self.append_result(f"    ignored: {r}")

        local_calib = {f: calib for f in valid_files}

        # create processing folder inside this subfolder
        proc_folder = self._create_unique_folder(folder)
        self.append_result(f"  Processing folder: {proc_folder}")

        # split
        sf_n = int(self.split_factor.get())
        for idx, img_name in enumerate(valid_files, start=1):
            img = Image.open(os.path.join(folder, img_name))
            w, h = img.size
            step_w, step_h = w // sf_n, h // sf_n
            crop_idx = 0
            for i in range(sf_n):
                for j in range(sf_n):
                    crop = img.crop((j * step_w, i * step_h,
                                     j * step_w + step_w, i * step_h + step_h))
                    if self.modality.get() == 'grey':
                        crop = crop.convert('L')
                    crop.save(os.path.join(
                        proc_folder,
                        f"{os.path.splitext(img_name)[0]}_crop{crop_idx + 1}.png"))
                    crop_idx += 1
            self.set_status(f"[{folder_name}] Split {idx}/{len(valid_files)}")

        # load model and predict
        model_rel = os.path.join('model', self.modality.get(),
                                 f'yolo11_{self.model_size.get()}', 'best.pt')
        model_path = resource_path(model_rel)
        if not os.path.exists(model_path):
            self.append_result(f"  [ERROR] Model not found: {model_path}")
            return
        model = ultralytics.YOLO(model_path)

        results = model.predict(
            source=proc_folder, save=True, save_txt=True, save_conf=True,
            project=proc_folder, conf=float(self.conf_thresh.get()), stream=True
        )
        for _ in results:
            pass  # consume stream to completion

        predict_root = os.path.join(proc_folder, 'predict')
        labels_dir = os.path.join(predict_root, 'labels')
        if not os.path.exists(labels_dir):
            self.append_result(f"  [WARN] No labels produced for {folder_name}")
            return

        # analyse
        dim_list, count_edge, count_inter = [], 0, 0
        for lab in sorted(f for f in os.listdir(labels_dir) if f.endswith('.txt')):
            base = os.path.splitext(lab)[0]
            img_candidate = None
            for ext in ('.png', '.jpg', '.jpeg'):
                p = os.path.join(predict_root, base + ext)
                if os.path.exists(p):
                    img_candidate = p
                    break
            if img_candidate is None:
                continue

            # recover calibration from original filename
            crop_base = os.path.basename(img_candidate).rsplit('_crop', 1)[0]
            mu = calib  # fallback
            for ext in ('.png', '.jpg', '.jpeg'):
                cand = crop_base + ext
                if cand in local_calib:
                    mu = float(local_calib[cand])
                    break

            w_img, h_img = Image.open(img_candidate).size
            with open(os.path.join(labels_dir, lab)) as fh:
                for line in fh:
                    parts = line.strip().split()
                    if len(parts) >= 6:
                        try:
                            _, xc, yc, wbox, hbox, conf = map(float, parts[:6])
                            if conf >= float(self.conf_thresh.get()):
                                W = wbox * w_img
                                H = hbox * h_img
                                max_dim = max(W, H)
                                min_dim = min(W, H)
                                if min_dim <= 0.5 * max_dim:
                                    count_edge += 1
                                else:
                                    count_inter += 1
                                dim = np.sqrt(max_dim**2 + min_dim**2) / np.sqrt(2)
                                dim_list.append(dim * mu)
                        except Exception:
                            continue

        if not dim_list:
            self.append_result(f"  [{folder_name}] No GUVs detected.")
            return

        arr = np.array(dim_list)
        median = np.median(arr)
        q1, q3 = np.percentile(arr, 25), np.percentile(arr, 75)
        try:
            shape, loc, scale = lognorm.fit(arr, floc=0)
            mu_ln, sigma_ln = float(np.log(scale)), float(shape)
        except Exception:
            shape = loc = scale = None
            mu_ln = sigma_ln = float('nan')

        # plot — saved to disk only, does not replace the global UI plot
        fig = Figure(figsize=(10, 6), tight_layout=True)
        ax = fig.add_subplot(111)
        bin_width = 5
        bins = np.arange(0, max(dim_list) + bin_width, bin_width)
        ax.hist(dim_list, bins=bins, color='steelblue', alpha=0.5, density=True)
        ax.axvline(median, color='darkred', linestyle='dashed', linewidth=3,
                   label=f'Median: {median:.2f} um')
        ax.axvline(q1, color='red', linestyle='dashed', linewidth=3,
                   label=f'Q1: {q1:.2f} um')
        ax.axvline(q3, color='red', linestyle='dashed', linewidth=3,
                   label=f'Q3: {q3:.2f} um')
        if shape is not None:
            x = np.linspace(0, max(dim_list), 1000)
            ax.plot(x, lognorm.pdf(x, shape, loc=loc, scale=scale), 'k-', linewidth=3,
                    label=(f'Log-normal fit\nmu={mu_ln:.2f}, sigma={sigma_ln:.2f}\n'
                           f'Total GUVs: {len(dim_list)}'))
        ax.set_xlabel('GUV Diameter (um)', fontsize=20)
        ax.set_ylabel('Density of GUVs', fontsize=20)
        ax.set_title(folder_name, fontsize=16)
        ax.tick_params(axis='both', which='major', labelsize=16)
        ax.legend(fontsize=16)
        ax.grid(linestyle=':')

        plot_path = os.path.join(proc_folder, f'{folder_name}.pdf')
        fig.savefig(plot_path, dpi=300, bbox_inches='tight')

        # CSV
        csv_path = os.path.join(proc_folder, f'{folder_name}.csv')
        with open(csv_path, mode='w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["GUV_ID", "Diameter_um"])
            for i, d in enumerate(dim_list, start=1):
                writer.writerow([i, f"{d:.4f}"])

        # JSON — temporarily swap current_folder_name so create_json uses the
        # subfolder name for the output filename, then restore it
        saved_name = self.current_folder_name
        self.current_folder_name = folder_name
        self.create_json(proc_folder)
        self.current_folder_name = saved_name

        # text summary for this subfolder
        self.append_result(f"  GUVs: {len(arr)}  |  Edge: {count_edge}  |  Interior: {count_inter}")
        self.append_result(f"  Median: {median:.2f} um  Q1: {q1:.2f} um  Q3: {q3:.2f} um")
        self.append_result(f"  Log-normal  mu={mu_ln:.2f}, sigma={sigma_ln:.2f}")
        self.append_result(f"  Plot: {plot_path}")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def read_pred_boxes(self, pred_path):
        boxes = []
        if os.path.exists(pred_path):
            with open(pred_path) as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) >= 6:
                        cls, xc, yc, w, h, conf = map(float, parts[:6])
                        if conf >= float(self.conf_thresh.get()):
                            boxes.append([xc, yc, w, h, conf])
        return boxes

    def create_json(self, folder_path):
        document_root = os.path.dirname(folder_path)
        folder_name = os.path.basename(folder_path)
        valid_ext = (".png", ".jpg", ".jpeg", ".bmp", ".tiff")
        images = [f for f in os.listdir(os.path.join(document_root, folder_name))
                  if f.lower().endswith(valid_ext)]

        if not images:
            print("No images found in the folder.")
            return document_root, folder_name

        json_list = []
        for img_name in images:
            abs_path = os.path.join(folder_name, img_name)
            ls_path = f"/data/local-files/?d={abs_path}"
            json_data = {
                "data": {"image": ls_path},
                "annotations": [],
                "predictions": []
            }
            labels = os.path.join(document_root, folder_name, "predict", "labels")
            image_path = os.path.join(document_root, folder_name, img_name)
            W, H = Image.open(image_path).size
            if os.path.exists(labels):
                result = []
                stem = os.path.splitext(img_name)[0]
                for bbox in self.read_pred_boxes(os.path.join(labels, stem + ".txt")):
                    xc, yc, w, h, c = bbox
                    x1 = xc - w / 2
                    y1 = yc - h / 2
                    result.append({
                        "original_width": W,
                        "original_height": H,
                        "image_rotation": 0,
                        "value": {
                            "x": x1 * 100, "y": y1 * 100,
                            "width": w * 100, "height": h * 100,
                            'rotation': 0, 'rectanglelabels': ['Empty_GUV']
                        },
                        "from_name": "label",
                        "to_name": "image",
                        'type': 'rectanglelabels',
                        'origin': 'manual'
                    })
                json_data["predictions"] = [{'result': result}]
            else:
                print(f"No preannotation found for {img_name}")
            json_list.append(json_data)

        json_file_path = os.path.join(document_root, folder_name,
                                      f"{self.current_folder_name}.json")
        with open(json_file_path, "w") as json_file:
            json.dump(json_list, json_file, indent=4)

        return document_root, folder_name

    def _get_mu_for_cropped(self, cropped_name):
        base = cropped_name.rsplit('_crop', 1)[0]
        for ext in ('.png', '.jpg', '.jpeg'):
            cand = base + ext
            if cand in self.calibration_data:
                return float(self.calibration_data[cand])
        if self.calibration_data:
            return float(next(iter(self.calibration_data.values())))
        return self.mu_per_pixel.get()

    def _show_plot(self, fig):
        for w in self.plot_frame.winfo_children():
            w.destroy()
        canvas = FigureCanvasTkAgg(fig, master=self.plot_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)
        self.notebook.select(1)

    def _create_unique_folder(self, parent_folder):
        base_name = PROCESSING_FOLDER_PREFIX
        sub_folder = os.path.join(parent_folder, base_name)
        if not os.path.exists(sub_folder):
            os.makedirs(sub_folder)
            return sub_folder
        counter = 2
        while True:
            new_name = f"{base_name}_{counter}"
            sub_folder = os.path.join(parent_folder, new_name)
            if not os.path.exists(sub_folder):
                os.makedirs(sub_folder)
                return sub_folder
            counter += 1


def main():
    root = tk.Tk()
    app = GUVDetectorGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()