FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt

COPY guv_detection/tools/inference.py guv_detection/tools/inference.py
COPY guv_detection/app/model guv_detection/app/model

ENTRYPOINT ["python", "guv_detection/tools/inference.py"]
